version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Starting build phase"
      - echo "Hello from CodeBuild 👋"
      - echo "Date: $(date)"
      - echo "Build ID: $CODEBUILD_BUILD_ID"
      - echo "Commit: $CODEBUILD_RESOLVED_SOURCE_VERSION"

artifacts:
  files:
    - "**/*"
