version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencis..."
  build:
    commands:
      - echo "Starting build phase"
      - echo "Hello from CodeBuid 👋"
      - echo "Date: $(date)"

artifacts:
  files:
    - "**/*"
